### ISSUE TITLE
btest -a debug, TEST_TRACE_COMMANDS and set -x gotcha

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek-testing-cluster#17]
This may be rather subjective and more of a gotcha, but I spent longer than I want to admit wondering where the output goes, so leaving a note here. There may be nothing to fix here. Though I could make a stance that `TEST_TRACE_COMMANDS` shouldn't be set within the environment for the `-a debug` or `-a debug-failures` given that the docs around them are about when containers are stopped/cleaned.

I have developed a pattern of putting `set -x` at the top of a testing script to get as much output as possible to `.stderr` when a test doesn't work as expected (sometimes leaving it there to have the details when a test breaks spuriously or eventually). Within this project, this approach doesn't work when the `-a debug` and `-a debug-failures` environments are used due to the TEST_TRACE_COMMANDS functionality hooking into bash's tracing. I think I'd prefer this feature not to be enabled implicitly.

**Comment by ckreibich** [comment]
I think part of the question here is what you're expecting to see with "the output", because it can be many things here — output from the commands in a test, the `docker-compose` logs, the Zeek logs, etc. I've found that for most of my test troubleshooting I now go straight into the Zeek logs that the tests copy out of the container instances, and not so much the "traditional" stdout/stderr output.

I'm guessing that since the overall setup didn't work for you out of the box, you probably spent more time digging into the test harness itself. If you'd like to see the latter work differently, I'm all up for it — the `TEST_TRACE_COMMANDS` approach was something I tucked on early on and have actually never used much.

**Comment by awelzel** [comment]
> If you'd like to see the latter work differently, I'm all up for it

I think I'd just propose to remove it altogether. As you say, it was mostly around debugging the test harness and the docker-compose/docker/container setup and less so about actual Zeek behavior, and `set -x` and looking `.stderr` seems for me the okayish tool. But, I'm going to close this issue - removing TEST_TRACE_COMMANDS locally from btest.cfg made it go out of my way :-)
