### ISSUE TITLE
RFC: Run btest with -d by default to make error details more accessible?

### ISSUE THREAD

**Issue by awelzel** [zeek/zeek-testing-cluster#20]
In [this job](https://github.com/zeek/zeek/actions/runs/3581899543/jobs/6026452117), the get-id-value test failed due to listing/diffing all active log streams and the MQTT logs being added*

This, however, is not obvious from looking at the GitHub action: One needs to download (well, first find...) the cluster-btest.zip artifacts, unpack them, find the .diag file and look into it. It would be much nicer if there were more error details immediately visible within the GitHub action. I think `-d` does that, but we don't seem to use it in other external testing - any reasons I'm glaring over? Too much potential output?

*Could also consider removing the usage of active log streams to avoid the ripple effect into sub repositories.

**Comment by ckreibich** [comment]
Sorry for the delay here, Arne. I don't think you're overlooking anything, it's just that the invocations are a bit fractured. In the CI setup's `test.sh` we actually use `-d` for the Zeek's own btests and the `zeek-testing` external suite. For the private one we don't, since we don't want to leak sensitive details to the console, see [here](https://github.com/zeek/zeek/blob/master/ci/test.sh#L95-L96).

The `test.sh` script does not cover the cluster testsuite, so I think the right next step for this is to expand your new Cirrus-based invocation of the cluster testsuite to invoke it suitably. We could add a `btest-verbose-ci` target to the Makefile, make `btest-verbose` smart enough to detect when it's running in CI so it adds  `-d`, or spell out the btest invocation directly in .cirrus.yml.
